### ISSUE TITLE
has artscilab site been hacked

### ISSUE THREAD

**Issue by rmalina** [artscilab/admin#46]
UT Dallas ArtSciLab | Transdisciplinary art-science research lab at the ...
artscilab.atec.io/
This site may be hacked.
The ArtSciLab is a transdisciplinary research lab that carries out national and international ... Director of Design and Research for the ArtSciLab Cassini…
You've visited this page 2 times. Last visit: 7/21/16

**Comment by cassininazir** [comment]
I've inspected the code of the pages they think has been spammed. No indication of that from code inspection. Will have @colin-c take a closer look at locking this down using TLS encryption. 

Submitted to Google for second review.  
![screen shot 2016-09-06 at 11 21 48 am](https://cloud.githubusercontent.com/assets/1661430/18281850/224bc664-7424-11e6-9499-777a0cb893ac.png)
