### ISSUE TITLE
urgent fix to art scilab web site

### ISSUE THREAD

**Issue by rmalina** [artscilab/admin#48]
cassini

urgent

i am no longer associate director of atec

can you have zura remove this quickly

roger

He is currently a Distinguished Professor of Art and Technology and Professor of Physics, at the University of Texas at Dallas and Directeur de Recherche for the CNRS in France. He serves as the Associate Director of ATEC, and founded the ArtSciLab in the ATEC program fall 2013.

**Comment by cassininazir** [comment]
This has been fixed.
