### ISSUE TITLE
Update ArtSciLab People Page

### ISSUE THREAD

**Issue by cassininazir** [artscilab/admin#52]
http://artscilab.atec.io/people/

Alums:
- Corey Smart
- Indu Panchineni
- Lina Moon

Add new folks:
- Shruthy
- Emma
- Yana
- Anyone else on People page that I've forgotten

**Comment by EmmaNewkirk** [comment]
Names are in, will update again when I get photos of everyone

**Comment by cassininazir** [comment]
Great turnaround! Especially because you're new to WordPress!

**Comment by EmmaNewkirk** [comment]
Is there a difference between people who are in the lab and just associated with the lab? Alex and Ritwik are currently sitting in the lab but aren't on the people spreadsheet or the website

**Comment by cassininazir** [comment]
Add 
- Alex T. G.
- Ritwik
